# Generated by Django 2.2 on 2019-04-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsdatetime',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adsdatetimes', to='main.Report'),
            preserve_default=False,
        ),
    ]
