# Generated by Django 2.2 on 2019-04-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adsdatetime_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsdatetime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='adsdatetime',
            name='time',
        ),
        migrations.AddField(
            model_name='adsdatetime',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
